### ISSUE TITLE
Не работает установка

### ISSUE THREAD

**Issue by gwynnbleiidd** [ikantam/repucaution#1]
После разархивации и инструкциям из руководства ничего не происходит.
Всё что нужно для работы стоит, но при обращении просто белый экран.

Файл htaccess, который вы указываете в руководстве занесён у вас в gitignore.
Другого руководства я не нашёл.

**Comment by BeeR13** [comment]
Попробуйте сменить режим в index.php на development и посмотреть ошибки. Скорее всего с правами что-то. Права на запись у пользователя под которым запускается должны быть для application/cache и public/uploads

**Comment by gwynnbleiidd** [comment]
Этих папок не было в архиве, потому создавал руками, права точно есть.
А вот ругается он на:
```
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid CodeIgniter system path (system/).' in /home/admin/web/dir/public_html/vendor/lightsuner/stack-codeigniter/src/CodeIgniter/BaseApplication.php:494 Stack trace: #0 /home/admin/web/dir/public_html/vendor/lightsuner/stack-codeigniter/src/CodeIgniter/BaseApplication.php(468): StackCI\CodeIgniter\BaseApplication->defineSystemFolder() #1 /home/admin/web/dir/public_html/vendor/lightsuner/stack-codeigniter/src/CodeIgniter/BaseApplication.php(132): StackCI\CodeIgniter\BaseApplication->defineConstants() #2 /home/admin/web/dir/public_html/index.php(34): StackCI\CodeIgniter\BaseApplication->init() #3 {main} thrown in /home/admin/web/dir/public_html/vendor/lightsuner/stack-codeigniter/src/CodeIgniter/BaseApplication.php on line 494

**Comment by gwynnbleiidd** [comment]
Понял, почему-то половины файлов нет в архиве.
Сейчас выкачал снова, вроде есть и htaccess и папка systems.

Пойду проверять.

P.S: В архиве, который лежит на вашем сайте точно нету.

**Comment by BeeR13** [comment]
А папка system в корне есть?

**Comment by BeeR13** [comment]
Спасибо, архив на сайте сейчас заменим.

**Comment by gwynnbleiidd** [comment]
Немного сторонний вопрос, ВК часом нет в планах?

**Comment by BeeR13** [comment]
Пока нет, но все возможно.

**Comment by gwynnbleiidd** [comment]
Так, залил обновление.
Переключил в режим девелопера, прописал путь к базе. Но ругается что не может подключиться.
Ошибка в самом окне
```A Database Error Occurred
```Unable to connect to your database server using the provided settings.
```Filename: third_party/MX/Loader.php
```Line Number: 102
Есть ещё 20 строк, но я так понял это просто информационные.

**Comment by BeeR13** [comment]
Добавил коммит, там файлов драйвера не хватает. Обновите.

**Comment by gwynnbleiidd** [comment]
Подтянул, но всё равно не хочет подключатся.


```A Database Error Occurred
```Unable to connect to your database server using the provided settings.
```Filename: third_party/datamapper/system/DB.php
```Line Number: 150

Выше начал выводить:
```Exception: Symfony\Component\HttpKernel\Exception\HttpException. Line: 65. File: /home/admin/web/___public_html/smm/vendor/lightsuner/stack-codeigniter/src/CodeIgniter/Ext/core/Exceptions.php

**Comment by gwynnbleiidd** [comment]
Привет, поставил на тестовый сервер.
Всё с первого раза) Вопрос такой, конфликт с mode_pagespeed может быть? Ума не приложу, что конфликтует на живом сервере.

**Comment by BeeR13** [comment]
Да не должно, хотя я на серваках его не использовал.
