### ISSUE TITLE
installation not working

### ISSUE THREAD

**Issue by dio007** [ikantam/repucaution#2]
<img width="1255" alt="screen shot 2016-01-11 at 12 55 50 pm" src="https://cloud.githubusercontent.com/assets/16250395/12243177/bb2eaa96-b862-11e5-9ac8-edf8c4d6a5b7.png">
can't get to admin dashboard!! i try your suggestion migrate/index/59  but not working either , try reinstalling fresh ubuntu 14.04 and php 5.3.0 but same result, please help!!

**Comment by bulletproofsysadmin** [comment]
It was my experience you needed at least PHP 5.4.  Their documentation was a bit off on the minimums...

**Comment by dio007** [comment]
updated php 5.5.27 but still same results, can't get to admin dashboard, any suggestions?

**Comment by bulletproofsysadmin** [comment]
It had to be 5.4 in my testing.  I did a ton of work to get this app installed.  In the end I decided to use sprout social.  Let me know if you get it working.  I'd be very interested to see your instructions.

**Comment by dio007** [comment]
instructions need improvement, I will try my best to make this work, i will keep you inform

**Comment by BeeR13** [comment]
Please add record in users_groups table with user_id = 2 and group_id = 1.
